digraph Roadmap {
  node [color=red]

  define(`digraph',`subgraph')
  include(grammar/tsql_file.dot)
  include(grammar/batch.dot)
  include(grammar/execute_body_batch.dot)
  include(grammar/go_statement.dot)
  include(grammar/execute_statement_arg.dot)
  include(grammar/execute_statement_arg_named.dot)
  include(grammar/execute_statement_arg_unnamed.dot)
  include(grammar/func_proc_name_server_database_schema.dot)
  include(grammar/func_proc_name_database_schema.dot)
  include(grammar/func_proc_name_schema.dot)

  ## TODO
  include(grammar/sql_clauses.dot)
  include(grammar/dml_clause.dot)
  include(grammar/select_statement_standalone.dot)
  include(grammar/with_expression.dot)
  include(grammar/select_statement.dot)
  include(grammar/query_expression.dot)
  include(grammar/for_clause.dot)
  include(grammar/option_clause.dot)
  include(grammar/select_order_by_clause.dot)
  include(grammar/unions.dot)
  include(grammar/sql_union.dot)

  include(grammar/assignment_operator.dot)
  include(grammar/query_specification.dot)
  include(grammar/select_list.dot)
  include(grammar/select_list_elem.dot)
  include(grammar/top_clause.dot)

  include(grammar/create_or_alter_function.dot)
  include(grammar/create_or_alter_procedure.dot)
  include(grammar/create_or_alter_trigger.dot)
  include(grammar/create_view.dot)
  include(grammar/expression_elem.dot)
  include(grammar/group_by_item.dot)
  include(grammar/grouping_sets_item.dot)
  include(grammar/search_condition.dot)
  include(grammar/table_name.dot)
  include(grammar/table_sources.dot)
  include(grammar/udt_elem.dot)
  include(grammar/as_column_alias.dot)
  include(grammar/column_alias.dot)
  include(grammar/execute_var_string.dot)
  include(grammar/udt_method_arguments.dot)

  include(grammar/expression.dot)
  include(grammar/COLLATE.dot)
  include(grammar/DOLLAR_ACTION.dot)
  include(grammar/bracket_expression.dot)
  include(grammar/case_expression.dot)
  include(grammar/exist_call.dot)
  include(grammar/full_column_name.dot)
  include(grammar/function_call.dot)
  include(grammar/hierarchyid_call.dot)
  include(grammar/modify_call.dot)
  include(grammar/over_clause.dot)
  include(grammar/primitive_expression.dot)
  include(grammar/query_call.dot)
  include(grammar/time_zone.dot)
  include(grammar/unary_operator_expression.dot)
  include(grammar/value_call.dot)

  include(grammar/batch_level_statement.dot)
}
