#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 17

enum ts_symbol_identifiers {
  aux_sym_go_statement_token1 = 1,
  anon_sym_COMMA = 2,
  anon_sym_SEMI = 3,
  aux_sym_func_proc_name_server_database_schema_token1 = 4,
  aux_sym_execute_statement_arg_named_token1 = 5,
  anon_sym_EQ = 6,
  aux_sym_constant_token1 = 7,
  aux_sym_query_specification_token1 = 8,
  aux_sym_query_specification_token2 = 9,
  aux_sym_select_list_elem_token1 = 10,
  aux_sym_select_list_elem_token2 = 11,
  sym_integer = 12,
  anon_sym_TODO = 13,
  sym_tsql_file = 14,
  sym_batch = 15,
  sym_go_statement = 16,
  sym_execute_body_batch = 17,
  sym_func_proc_name_server_database_schema = 18,
  sym_func_proc_name_database_schema = 19,
  sym_func_proc_name_schema = 20,
  sym_execute_statement_arg = 21,
  sym_execute_statement_arg_named = 22,
  sym_execute_parameter = 23,
  sym_constant = 24,
  sym_sql_clauses = 25,
  sym_dml_clause = 26,
  sym_select_statement_standalone = 27,
  sym_select_statement = 28,
  sym_query_expression = 29,
  sym_query_specification = 30,
  sym_select_list = 31,
  sym_select_list_elem = 32,
  sym_table_sources = 33,
  sym_table_source = 34,
  sym_table_source_item = 35,
  sym_full_table_name = 36,
  sym_id_ = 37,
  sym_keyword = 38,
  aux_sym_tsql_file_repeat1 = 39,
  aux_sym_tsql_file_repeat2 = 40,
  aux_sym_batch_repeat1 = 41,
  aux_sym_execute_body_batch_repeat1 = 42,
  aux_sym_execute_statement_arg_repeat1 = 43,
  aux_sym_select_list_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_go_statement_token1] = "go_statement_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [aux_sym_func_proc_name_server_database_schema_token1] = "func_proc_name_server_database_schema_token1",
  [aux_sym_execute_statement_arg_named_token1] = "execute_statement_arg_named_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_constant_token1] = "constant_token1",
  [aux_sym_query_specification_token1] = "query_specification_token1",
  [aux_sym_query_specification_token2] = "query_specification_token2",
  [aux_sym_select_list_elem_token1] = "select_list_elem_token1",
  [aux_sym_select_list_elem_token2] = "select_list_elem_token2",
  [sym_integer] = "integer",
  [anon_sym_TODO] = "dummy",
  [sym_tsql_file] = "tsql_file",
  [sym_batch] = "batch",
  [sym_go_statement] = "go_statement",
  [sym_execute_body_batch] = "execute_body_batch",
  [sym_func_proc_name_server_database_schema] = "func_proc_name_server_database_schema",
  [sym_func_proc_name_database_schema] = "func_proc_name_database_schema",
  [sym_func_proc_name_schema] = "func_proc_name_schema",
  [sym_execute_statement_arg] = "execute_statement_arg",
  [sym_execute_statement_arg_named] = "execute_statement_arg_named",
  [sym_execute_parameter] = "execute_parameter",
  [sym_constant] = "constant",
  [sym_sql_clauses] = "sql_clauses",
  [sym_dml_clause] = "dml_clause",
  [sym_select_statement_standalone] = "select_statement_standalone",
  [sym_select_statement] = "select_statement",
  [sym_query_expression] = "query_expression",
  [sym_query_specification] = "query_specification",
  [sym_select_list] = "select_list",
  [sym_select_list_elem] = "select_list_elem",
  [sym_table_sources] = "table_sources",
  [sym_table_source] = "table_source",
  [sym_table_source_item] = "table_source_item",
  [sym_full_table_name] = "full_table_name",
  [sym_id_] = "id_",
  [sym_keyword] = "keyword",
  [aux_sym_tsql_file_repeat1] = "tsql_file_repeat1",
  [aux_sym_tsql_file_repeat2] = "tsql_file_repeat2",
  [aux_sym_batch_repeat1] = "batch_repeat1",
  [aux_sym_execute_body_batch_repeat1] = "execute_body_batch_repeat1",
  [aux_sym_execute_statement_arg_repeat1] = "execute_statement_arg_repeat1",
  [aux_sym_select_list_repeat1] = "select_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_go_statement_token1] = aux_sym_go_statement_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_func_proc_name_server_database_schema_token1] = aux_sym_func_proc_name_server_database_schema_token1,
  [aux_sym_execute_statement_arg_named_token1] = aux_sym_execute_statement_arg_named_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [aux_sym_query_specification_token1] = aux_sym_query_specification_token1,
  [aux_sym_query_specification_token2] = aux_sym_query_specification_token2,
  [aux_sym_select_list_elem_token1] = aux_sym_select_list_elem_token1,
  [aux_sym_select_list_elem_token2] = aux_sym_select_list_elem_token2,
  [sym_integer] = sym_integer,
  [anon_sym_TODO] = anon_sym_TODO,
  [sym_tsql_file] = sym_tsql_file,
  [sym_batch] = sym_batch,
  [sym_go_statement] = sym_go_statement,
  [sym_execute_body_batch] = sym_execute_body_batch,
  [sym_func_proc_name_server_database_schema] = sym_func_proc_name_server_database_schema,
  [sym_func_proc_name_database_schema] = sym_func_proc_name_database_schema,
  [sym_func_proc_name_schema] = sym_func_proc_name_schema,
  [sym_execute_statement_arg] = sym_execute_statement_arg,
  [sym_execute_statement_arg_named] = sym_execute_statement_arg_named,
  [sym_execute_parameter] = sym_execute_parameter,
  [sym_constant] = sym_constant,
  [sym_sql_clauses] = sym_sql_clauses,
  [sym_dml_clause] = sym_dml_clause,
  [sym_select_statement_standalone] = sym_select_statement_standalone,
  [sym_select_statement] = sym_select_statement,
  [sym_query_expression] = sym_query_expression,
  [sym_query_specification] = sym_query_specification,
  [sym_select_list] = sym_select_list,
  [sym_select_list_elem] = sym_select_list_elem,
  [sym_table_sources] = sym_table_sources,
  [sym_table_source] = sym_table_source,
  [sym_table_source_item] = sym_table_source_item,
  [sym_full_table_name] = sym_full_table_name,
  [sym_id_] = sym_id_,
  [sym_keyword] = sym_keyword,
  [aux_sym_tsql_file_repeat1] = aux_sym_tsql_file_repeat1,
  [aux_sym_tsql_file_repeat2] = aux_sym_tsql_file_repeat2,
  [aux_sym_batch_repeat1] = aux_sym_batch_repeat1,
  [aux_sym_execute_body_batch_repeat1] = aux_sym_execute_body_batch_repeat1,
  [aux_sym_execute_statement_arg_repeat1] = aux_sym_execute_statement_arg_repeat1,
  [aux_sym_select_list_repeat1] = aux_sym_select_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_go_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_func_proc_name_server_database_schema_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_statement_arg_named_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_specification_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_specification_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_elem_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_elem_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TODO] = {
    .visible = true,
    .named = true,
  },
  [sym_tsql_file] = {
    .visible = true,
    .named = true,
  },
  [sym_batch] = {
    .visible = true,
    .named = true,
  },
  [sym_go_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_body_batch] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_server_database_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_database_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_statement_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_statement_arg_named] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_clauses] = {
    .visible = true,
    .named = true,
  },
  [sym_dml_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement_standalone] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_query_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_query_specification] = {
    .visible = true,
    .named = true,
  },
  [sym_select_list] = {
    .visible = true,
    .named = true,
  },
  [sym_select_list_elem] = {
    .visible = true,
    .named = true,
  },
  [sym_table_sources] = {
    .visible = true,
    .named = true,
  },
  [sym_table_source] = {
    .visible = true,
    .named = true,
  },
  [sym_table_source_item] = {
    .visible = true,
    .named = true,
  },
  [sym_full_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_id_] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tsql_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tsql_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_batch_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_body_batch_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_statement_arg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_database = 2,
  field_name = 3,
  field_procedure = 4,
  field_schema = 5,
  field_server = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_database] = "database",
  [field_name] = "name",
  [field_procedure] = "procedure",
  [field_schema] = "schema",
  [field_server] = "server",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 3},
  [13] = {.index = 21, .length = 3},
  [14] = {.index = 24, .length = 3},
  [15] = {.index = 27, .length = 3},
  [16] = {.index = 30, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_procedure, 0},
  [1] =
    {field_count, 1},
  [2] =
    {field_procedure, 2},
  [3] =
    {field_procedure, 2},
    {field_schema, 0},
  [5] =
    {field_procedure, 3},
  [6] =
    {field_procedure, 3},
    {field_schema, 1},
  [8] =
    {field_name, 0},
    {field_value, 2},
  [10] =
    {field_database, 0},
    {field_procedure, 3},
  [12] =
    {field_procedure, 4},
    {field_schema, 2},
  [14] =
    {field_database, 1},
    {field_procedure, 4},
  [16] =
    {field_procedure, 4},
    {field_server, 0},
  [18] =
    {field_database, 0},
    {field_procedure, 4},
    {field_schema, 2},
  [21] =
    {field_database, 1},
    {field_procedure, 5},
    {field_schema, 3},
  [24] =
    {field_procedure, 5},
    {field_schema, 3},
    {field_server, 0},
  [27] =
    {field_database, 2},
    {field_procedure, 5},
    {field_server, 0},
  [30] =
    {field_database, 2},
    {field_procedure, 6},
    {field_schema, 4},
    {field_server, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 28,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 27,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 17,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 32,
  [92] = 44,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\'', 2,
        ',', 20,
        '.', 22,
        ';', 21,
        '=', 24,
        '@', 13,
        'N', 29,
        'T', 31,
        '[', 12,
        'F', 40,
        'f', 40,
        'G', 38,
        'g', 38,
        'S', 34,
        's', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '[') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\'', 2,
        ',', 20,
        '.', 22,
        ';', 21,
        '@', 13,
        'N', 1,
        'G', 10,
        'g', 10,
        'S', 7,
        's', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        ',', 20,
        '.', 22,
        ';', 21,
        '[', 12,
        'F', 40,
        'f', 40,
        'G', 38,
        'g', 38,
        'S', 34,
        's', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '.', 22,
        ';', 21,
        '@', 13,
        '[', 12,
        'G', 38,
        'g', 38,
        'S', 34,
        's', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_go_statement_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_go_statement_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_func_proc_name_server_database_schema_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_execute_statement_arg_named_token1);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_query_specification_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_query_specification_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_query_specification_token2);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'D') ADVANCE(32);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O') ADVANCE(30);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O') ADVANCE(45);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(41);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(35);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(28);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(37);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(39);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(27);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_TODO);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 14},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 14},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 14},
  [51] = {.lex_state = 14},
  [52] = {.lex_state = 14},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 14},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 14},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 14},
  [62] = {.lex_state = 14},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 14},
  [70] = {.lex_state = 14},
  [71] = {.lex_state = 14},
  [72] = {.lex_state = 14},
  [73] = {.lex_state = 14},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 14},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 14},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 14},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 14},
  [84] = {.lex_state = 14},
  [85] = {.lex_state = 14},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 14},
  [89] = {.lex_state = 14},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 14},
  [92] = {.lex_state = 14},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_go_statement_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym_func_proc_name_server_database_schema_token1] = ACTIONS(1),
    [aux_sym_execute_statement_arg_named_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_constant_token1] = ACTIONS(1),
    [aux_sym_query_specification_token1] = ACTIONS(1),
    [aux_sym_query_specification_token2] = ACTIONS(1),
    [aux_sym_select_list_elem_token1] = ACTIONS(1),
    [aux_sym_select_list_elem_token2] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_TODO] = ACTIONS(1),
  },
  [1] = {
    [sym_tsql_file] = STATE(95),
    [sym_batch] = STATE(3),
    [sym_go_statement] = STATE(22),
    [sym_execute_body_batch] = STATE(7),
    [sym_func_proc_name_server_database_schema] = STATE(36),
    [sym_func_proc_name_database_schema] = STATE(61),
    [sym_func_proc_name_schema] = STATE(74),
    [sym_sql_clauses] = STATE(5),
    [sym_dml_clause] = STATE(35),
    [sym_select_statement_standalone] = STATE(23),
    [sym_select_statement] = STATE(24),
    [sym_query_expression] = STATE(25),
    [sym_query_specification] = STATE(26),
    [sym_id_] = STATE(58),
    [sym_keyword] = STATE(38),
    [aux_sym_tsql_file_repeat1] = STATE(3),
    [aux_sym_batch_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_go_statement_token1] = ACTIONS(5),
    [aux_sym_func_proc_name_server_database_schema_token1] = ACTIONS(7),
    [aux_sym_query_specification_token1] = ACTIONS(9),
    [aux_sym_select_list_elem_token1] = ACTIONS(11),
    [aux_sym_select_list_elem_token2] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      aux_sym_go_statement_token1,
    ACTIONS(20), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(23), 1,
      aux_sym_query_specification_token1,
    ACTIONS(26), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(29), 1,
      aux_sym_select_list_elem_token2,
    STATE(10), 1,
      sym_execute_body_batch,
    STATE(22), 1,
      sym_go_statement,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(36), 1,
      sym_func_proc_name_server_database_schema,
    STATE(38), 1,
      sym_keyword,
    STATE(58), 1,
      sym_id_,
    STATE(61), 1,
      sym_func_proc_name_database_schema,
    STATE(74), 1,
      sym_func_proc_name_schema,
    STATE(2), 2,
      sym_batch,
      aux_sym_tsql_file_repeat1,
    STATE(5), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [63] = 20,
    ACTIONS(5), 1,
      aux_sym_go_statement_token1,
    ACTIONS(7), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(9), 1,
      aux_sym_query_specification_token1,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_execute_body_batch,
    STATE(22), 1,
      sym_go_statement,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(36), 1,
      sym_func_proc_name_server_database_schema,
    STATE(38), 1,
      sym_keyword,
    STATE(58), 1,
      sym_id_,
    STATE(61), 1,
      sym_func_proc_name_database_schema,
    STATE(74), 1,
      sym_func_proc_name_schema,
    STATE(2), 2,
      sym_batch,
      aux_sym_tsql_file_repeat1,
    STATE(5), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [126] = 11,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(39), 1,
      aux_sym_query_specification_token1,
    ACTIONS(42), 1,
      aux_sym_select_list_elem_token1,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    STATE(16), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [164] = 11,
    ACTIONS(46), 1,
      aux_sym_go_statement_token1,
    ACTIONS(49), 1,
      aux_sym_query_specification_token1,
    ACTIONS(52), 1,
      aux_sym_select_list_elem_token1,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    STATE(19), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [202] = 9,
    ACTIONS(58), 1,
      aux_sym_query_specification_token1,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    ACTIONS(56), 2,
      aux_sym_go_statement_token1,
      aux_sym_select_list_elem_token1,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [234] = 11,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      aux_sym_go_statement_token1,
    ACTIONS(63), 1,
      aux_sym_query_specification_token1,
    STATE(20), 1,
      sym_go_statement,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(83), 1,
      aux_sym_tsql_file_repeat2,
    STATE(4), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [269] = 4,
    ACTIONS(69), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(67), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [288] = 4,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(8), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(74), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [307] = 9,
    ACTIONS(61), 1,
      aux_sym_go_statement_token1,
    ACTIONS(63), 1,
      aux_sym_query_specification_token1,
    STATE(21), 1,
      sym_go_statement,
    STATE(23), 1,
      sym_select_statement_standalone,
    STATE(24), 1,
      sym_select_statement,
    STATE(25), 1,
      sym_query_expression,
    STATE(26), 1,
      sym_query_specification,
    STATE(35), 1,
      sym_dml_clause,
    STATE(4), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [336] = 4,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(9), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(80), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [355] = 2,
    ACTIONS(84), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [369] = 4,
    ACTIONS(92), 1,
      sym_integer,
    ACTIONS(90), 2,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(88), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [387] = 2,
    ACTIONS(67), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [401] = 9,
    ACTIONS(94), 1,
      aux_sym_go_statement_token1,
    ACTIONS(96), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(98), 1,
      aux_sym_select_list_elem_token2,
    STATE(28), 1,
      sym_keyword,
    STATE(29), 1,
      sym_id_,
    STATE(30), 1,
      sym_full_table_name,
    STATE(31), 1,
      sym_table_source_item,
    STATE(33), 1,
      sym_table_source,
    STATE(34), 1,
      sym_table_sources,
  [429] = 4,
    ACTIONS(102), 1,
      aux_sym_go_statement_token1,
    ACTIONS(105), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(17), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(100), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [446] = 4,
    ACTIONS(109), 1,
      aux_sym_go_statement_token1,
    ACTIONS(112), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(17), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [463] = 3,
    ACTIONS(118), 1,
      aux_sym_query_specification_token2,
    ACTIONS(116), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [478] = 4,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(17), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [495] = 5,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 1,
      aux_sym_go_statement_token1,
    ACTIONS(34), 2,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(16), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [514] = 4,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(16), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [531] = 3,
    STATE(19), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(52), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [546] = 2,
    ACTIONS(129), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [558] = 2,
    ACTIONS(133), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [570] = 2,
    ACTIONS(137), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [582] = 2,
    ACTIONS(141), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [594] = 2,
    ACTIONS(143), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(90), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [606] = 2,
    ACTIONS(147), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [618] = 2,
    ACTIONS(151), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [630] = 2,
    ACTIONS(155), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(153), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [642] = 2,
    ACTIONS(159), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(157), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [654] = 3,
    ACTIONS(92), 1,
      sym_integer,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(88), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [668] = 2,
    ACTIONS(163), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(161), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [680] = 2,
    ACTIONS(167), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(165), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [692] = 3,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(171), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [706] = 5,
    ACTIONS(177), 1,
      anon_sym_SEMI,
    ACTIONS(179), 1,
      aux_sym_execute_statement_arg_named_token1,
    STATE(39), 1,
      sym_execute_statement_arg,
    STATE(40), 1,
      sym_execute_statement_arg_named,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [724] = 2,
    ACTIONS(183), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [735] = 1,
    ACTIONS(145), 6,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [744] = 4,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_SEMI,
    STATE(54), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [759] = 2,
    STATE(56), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [770] = 2,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(195), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [781] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(199), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(37), 1,
      sym_id_,
    STATE(38), 1,
      sym_keyword,
  [800] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(201), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(96), 1,
      sym_id_,
  [819] = 2,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(205), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [830] = 1,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [839] = 2,
    ACTIONS(209), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [850] = 2,
    ACTIONS(213), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [861] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(215), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(55), 1,
      sym_id_,
  [880] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(217), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(46), 1,
      sym_id_,
  [899] = 2,
    ACTIONS(221), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [910] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(223), 4,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [923] = 3,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(228), 4,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [936] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(233), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(47), 1,
      sym_id_,
  [955] = 4,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_SEMI,
    STATE(52), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [970] = 2,
    ACTIONS(241), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(239), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [981] = 2,
    STATE(51), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(243), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [992] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    ACTIONS(245), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(50), 1,
      sym_id_,
  [1011] = 2,
    ACTIONS(249), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1022] = 1,
    ACTIONS(251), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1030] = 1,
    ACTIONS(253), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1038] = 1,
    ACTIONS(255), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1046] = 1,
    ACTIONS(257), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1054] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(59), 1,
      sym_id_,
  [1070] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(81), 1,
      sym_id_,
  [1086] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(62), 1,
      sym_id_,
  [1102] = 1,
    ACTIONS(259), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1110] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(66), 1,
      sym_id_,
  [1126] = 1,
    ACTIONS(261), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1134] = 1,
    ACTIONS(263), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1142] = 1,
    ACTIONS(265), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1150] = 1,
    ACTIONS(267), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1158] = 1,
    ACTIONS(228), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1166] = 1,
    ACTIONS(269), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1174] = 1,
    ACTIONS(271), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1182] = 1,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1190] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(68), 1,
      sym_id_,
  [1206] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(79), 1,
      sym_id_,
  [1222] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(73), 1,
      sym_id_,
  [1238] = 1,
    ACTIONS(273), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1246] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(197), 1,
      aux_sym_go_statement_token1,
    STATE(38), 1,
      sym_keyword,
    STATE(60), 1,
      sym_id_,
  [1262] = 1,
    ACTIONS(275), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_query_specification_token1,
  [1270] = 3,
    STATE(11), 1,
      sym_select_list_elem,
    STATE(18), 1,
      sym_select_list,
    ACTIONS(277), 2,
      aux_sym_select_list_elem_token1,
      aux_sym_select_list_elem_token2,
  [1281] = 3,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
    ACTIONS(281), 1,
      aux_sym_go_statement_token1,
    STATE(84), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [1292] = 3,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(283), 1,
      aux_sym_go_statement_token1,
    STATE(84), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [1303] = 3,
    ACTIONS(286), 1,
      aux_sym_constant_token1,
    STATE(70), 1,
      sym_execute_parameter,
    STATE(71), 1,
      sym_constant,
  [1313] = 3,
    ACTIONS(179), 1,
      aux_sym_execute_statement_arg_named_token1,
    STATE(40), 1,
      sym_execute_statement_arg_named,
    STATE(72), 1,
      sym_execute_statement_arg,
  [1323] = 2,
    STATE(14), 1,
      sym_select_list_elem,
    ACTIONS(277), 2,
      aux_sym_select_list_elem_token1,
      aux_sym_select_list_elem_token2,
  [1331] = 1,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1337] = 1,
    ACTIONS(288), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1343] = 1,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1349] = 2,
    ACTIONS(290), 1,
      sym_integer,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
  [1357] = 1,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
  [1362] = 2,
    ACTIONS(179), 1,
      aux_sym_execute_statement_arg_named_token1,
    STATE(75), 1,
      sym_execute_statement_arg_named,
  [1369] = 1,
    ACTIONS(292), 1,
      anon_sym_EQ,
  [1373] = 1,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
  [1377] = 1,
    ACTIONS(296), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 164,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 234,
  [SMALL_STATE(8)] = 269,
  [SMALL_STATE(9)] = 288,
  [SMALL_STATE(10)] = 307,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 369,
  [SMALL_STATE(14)] = 387,
  [SMALL_STATE(15)] = 401,
  [SMALL_STATE(16)] = 429,
  [SMALL_STATE(17)] = 446,
  [SMALL_STATE(18)] = 463,
  [SMALL_STATE(19)] = 478,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 514,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 546,
  [SMALL_STATE(24)] = 558,
  [SMALL_STATE(25)] = 570,
  [SMALL_STATE(26)] = 582,
  [SMALL_STATE(27)] = 594,
  [SMALL_STATE(28)] = 606,
  [SMALL_STATE(29)] = 618,
  [SMALL_STATE(30)] = 630,
  [SMALL_STATE(31)] = 642,
  [SMALL_STATE(32)] = 654,
  [SMALL_STATE(33)] = 668,
  [SMALL_STATE(34)] = 680,
  [SMALL_STATE(35)] = 692,
  [SMALL_STATE(36)] = 706,
  [SMALL_STATE(37)] = 724,
  [SMALL_STATE(38)] = 735,
  [SMALL_STATE(39)] = 744,
  [SMALL_STATE(40)] = 759,
  [SMALL_STATE(41)] = 770,
  [SMALL_STATE(42)] = 781,
  [SMALL_STATE(43)] = 800,
  [SMALL_STATE(44)] = 819,
  [SMALL_STATE(45)] = 830,
  [SMALL_STATE(46)] = 839,
  [SMALL_STATE(47)] = 850,
  [SMALL_STATE(48)] = 861,
  [SMALL_STATE(49)] = 880,
  [SMALL_STATE(50)] = 899,
  [SMALL_STATE(51)] = 910,
  [SMALL_STATE(52)] = 923,
  [SMALL_STATE(53)] = 936,
  [SMALL_STATE(54)] = 955,
  [SMALL_STATE(55)] = 970,
  [SMALL_STATE(56)] = 981,
  [SMALL_STATE(57)] = 992,
  [SMALL_STATE(58)] = 1011,
  [SMALL_STATE(59)] = 1022,
  [SMALL_STATE(60)] = 1030,
  [SMALL_STATE(61)] = 1038,
  [SMALL_STATE(62)] = 1046,
  [SMALL_STATE(63)] = 1054,
  [SMALL_STATE(64)] = 1070,
  [SMALL_STATE(65)] = 1086,
  [SMALL_STATE(66)] = 1102,
  [SMALL_STATE(67)] = 1110,
  [SMALL_STATE(68)] = 1126,
  [SMALL_STATE(69)] = 1134,
  [SMALL_STATE(70)] = 1142,
  [SMALL_STATE(71)] = 1150,
  [SMALL_STATE(72)] = 1158,
  [SMALL_STATE(73)] = 1166,
  [SMALL_STATE(74)] = 1174,
  [SMALL_STATE(75)] = 1182,
  [SMALL_STATE(76)] = 1190,
  [SMALL_STATE(77)] = 1206,
  [SMALL_STATE(78)] = 1222,
  [SMALL_STATE(79)] = 1238,
  [SMALL_STATE(80)] = 1246,
  [SMALL_STATE(81)] = 1262,
  [SMALL_STATE(82)] = 1270,
  [SMALL_STATE(83)] = 1281,
  [SMALL_STATE(84)] = 1292,
  [SMALL_STATE(85)] = 1303,
  [SMALL_STATE(86)] = 1313,
  [SMALL_STATE(87)] = 1323,
  [SMALL_STATE(88)] = 1331,
  [SMALL_STATE(89)] = 1337,
  [SMALL_STATE(90)] = 1343,
  [SMALL_STATE(91)] = 1349,
  [SMALL_STATE(92)] = 1357,
  [SMALL_STATE(93)] = 1362,
  [SMALL_STATE(94)] = 1369,
  [SMALL_STATE(95)] = 1373,
  [SMALL_STATE(96)] = 1377,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0), SHIFT(32),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0), SHIFT(82),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 1, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0), SHIFT(32),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0), SHIFT(82),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list_elem, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list_elem, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_statement, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_statement, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 3, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 3, 0, 0), SHIFT(32),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_specification, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_specification, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 1, 0, 0), REDUCE(sym_batch, 2, 0, 0),
  [123] = {.entry = {.count = 3, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 1, 0, 0), REDUCE(sym_batch, 2, 0, 0), SHIFT(32),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dml_clause, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dml_clause, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement_standalone, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_statement_standalone, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_statement, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_expression, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_expression, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_table_name, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_table_name, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_source_item, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_source_item, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_source, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_source, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_sources, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_sources, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_specification, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_specification, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sql_clauses, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sql_clauses, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_schema, 3, 0, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sql_clauses, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sql_clauses, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_statement, 2, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_statement, 2, 0, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 5, 0, 12),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 3, 0, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 4, 0, 8),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_execute_statement_arg_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_execute_statement_arg_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_execute_body_batch_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_execute_body_batch_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 4, 0, 6),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_schema, 1, 0, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 9),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 13),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 4, 0, 5),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 7, 0, 16),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 15),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg_named, 3, 0, 7),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_parameter, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 14),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 1, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 11),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 10),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0), SHIFT_REPEAT(91),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 4, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [294] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_TSQL(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
