#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 18

enum ts_symbol_identifiers {
  aux_sym_go_statement_token1 = 1,
  anon_sym_COMMA = 2,
  anon_sym_SEMI = 3,
  aux_sym_func_proc_name_server_database_schema_token1 = 4,
  aux_sym_execute_statement_arg_named_token1 = 5,
  anon_sym_EQ = 6,
  aux_sym_constant_token1 = 7,
  aux_sym_constant_token2 = 8,
  aux_sym_constant_token3 = 9,
  aux_sym_query_specification_token1 = 10,
  aux_sym_query_specification_token2 = 11,
  aux_sym_select_list_elem_token1 = 12,
  aux_sym_select_list_elem_token2 = 13,
  anon_sym_TODO = 14,
  sym_tsql_file = 15,
  sym_batch = 16,
  sym_go_statement = 17,
  sym_execute_body_batch = 18,
  sym_func_proc_name_server_database_schema = 19,
  sym_func_proc_name_database_schema = 20,
  sym_func_proc_name_schema = 21,
  sym_execute_statement_arg = 22,
  sym_execute_statement_arg_named = 23,
  sym_execute_statement_arg_unnamed = 24,
  sym_execute_parameter = 25,
  sym_constant = 26,
  sym_sql_clauses = 27,
  sym_dml_clause = 28,
  sym_select_statement_standalone = 29,
  sym_select_statement = 30,
  sym_query_expression = 31,
  sym_query_specification = 32,
  sym_select_list = 33,
  sym_select_list_elem = 34,
  sym_table_sources = 35,
  sym_table_source = 36,
  sym_table_source_item = 37,
  sym_full_table_name = 38,
  sym_id_ = 39,
  sym_keyword = 40,
  sym_integer = 41,
  aux_sym_tsql_file_repeat1 = 42,
  aux_sym_tsql_file_repeat2 = 43,
  aux_sym_batch_repeat1 = 44,
  aux_sym_execute_body_batch_repeat1 = 45,
  aux_sym_execute_statement_arg_repeat1 = 46,
  aux_sym_select_list_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_go_statement_token1] = "go_statement_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [aux_sym_func_proc_name_server_database_schema_token1] = "func_proc_name_server_database_schema_token1",
  [aux_sym_execute_statement_arg_named_token1] = "execute_statement_arg_named_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_constant_token1] = "constant_token1",
  [aux_sym_constant_token2] = "constant_token2",
  [aux_sym_constant_token3] = "constant_token3",
  [aux_sym_query_specification_token1] = "query_specification_token1",
  [aux_sym_query_specification_token2] = "query_specification_token2",
  [aux_sym_select_list_elem_token1] = "select_list_elem_token1",
  [aux_sym_select_list_elem_token2] = "select_list_elem_token2",
  [anon_sym_TODO] = "dummy",
  [sym_tsql_file] = "tsql_file",
  [sym_batch] = "batch",
  [sym_go_statement] = "go_statement",
  [sym_execute_body_batch] = "execute_body_batch",
  [sym_func_proc_name_server_database_schema] = "func_proc_name_server_database_schema",
  [sym_func_proc_name_database_schema] = "func_proc_name_database_schema",
  [sym_func_proc_name_schema] = "func_proc_name_schema",
  [sym_execute_statement_arg] = "execute_statement_arg",
  [sym_execute_statement_arg_named] = "execute_statement_arg_named",
  [sym_execute_statement_arg_unnamed] = "execute_statement_arg_unnamed",
  [sym_execute_parameter] = "execute_parameter",
  [sym_constant] = "constant",
  [sym_sql_clauses] = "sql_clauses",
  [sym_dml_clause] = "dml_clause",
  [sym_select_statement_standalone] = "select_statement_standalone",
  [sym_select_statement] = "select_statement",
  [sym_query_expression] = "query_expression",
  [sym_query_specification] = "query_specification",
  [sym_select_list] = "select_list",
  [sym_select_list_elem] = "select_list_elem",
  [sym_table_sources] = "table_sources",
  [sym_table_source] = "table_source",
  [sym_table_source_item] = "table_source_item",
  [sym_full_table_name] = "full_table_name",
  [sym_id_] = "id_",
  [sym_keyword] = "keyword",
  [sym_integer] = "integer",
  [aux_sym_tsql_file_repeat1] = "tsql_file_repeat1",
  [aux_sym_tsql_file_repeat2] = "tsql_file_repeat2",
  [aux_sym_batch_repeat1] = "batch_repeat1",
  [aux_sym_execute_body_batch_repeat1] = "execute_body_batch_repeat1",
  [aux_sym_execute_statement_arg_repeat1] = "execute_statement_arg_repeat1",
  [aux_sym_select_list_repeat1] = "select_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_go_statement_token1] = aux_sym_go_statement_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_func_proc_name_server_database_schema_token1] = aux_sym_func_proc_name_server_database_schema_token1,
  [aux_sym_execute_statement_arg_named_token1] = aux_sym_execute_statement_arg_named_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [aux_sym_constant_token2] = aux_sym_constant_token2,
  [aux_sym_constant_token3] = aux_sym_constant_token3,
  [aux_sym_query_specification_token1] = aux_sym_query_specification_token1,
  [aux_sym_query_specification_token2] = aux_sym_query_specification_token2,
  [aux_sym_select_list_elem_token1] = aux_sym_select_list_elem_token1,
  [aux_sym_select_list_elem_token2] = aux_sym_select_list_elem_token2,
  [anon_sym_TODO] = anon_sym_TODO,
  [sym_tsql_file] = sym_tsql_file,
  [sym_batch] = sym_batch,
  [sym_go_statement] = sym_go_statement,
  [sym_execute_body_batch] = sym_execute_body_batch,
  [sym_func_proc_name_server_database_schema] = sym_func_proc_name_server_database_schema,
  [sym_func_proc_name_database_schema] = sym_func_proc_name_database_schema,
  [sym_func_proc_name_schema] = sym_func_proc_name_schema,
  [sym_execute_statement_arg] = sym_execute_statement_arg,
  [sym_execute_statement_arg_named] = sym_execute_statement_arg_named,
  [sym_execute_statement_arg_unnamed] = sym_execute_statement_arg_unnamed,
  [sym_execute_parameter] = sym_execute_parameter,
  [sym_constant] = sym_constant,
  [sym_sql_clauses] = sym_sql_clauses,
  [sym_dml_clause] = sym_dml_clause,
  [sym_select_statement_standalone] = sym_select_statement_standalone,
  [sym_select_statement] = sym_select_statement,
  [sym_query_expression] = sym_query_expression,
  [sym_query_specification] = sym_query_specification,
  [sym_select_list] = sym_select_list,
  [sym_select_list_elem] = sym_select_list_elem,
  [sym_table_sources] = sym_table_sources,
  [sym_table_source] = sym_table_source,
  [sym_table_source_item] = sym_table_source_item,
  [sym_full_table_name] = sym_full_table_name,
  [sym_id_] = sym_id_,
  [sym_keyword] = sym_keyword,
  [sym_integer] = sym_integer,
  [aux_sym_tsql_file_repeat1] = aux_sym_tsql_file_repeat1,
  [aux_sym_tsql_file_repeat2] = aux_sym_tsql_file_repeat2,
  [aux_sym_batch_repeat1] = aux_sym_batch_repeat1,
  [aux_sym_execute_body_batch_repeat1] = aux_sym_execute_body_batch_repeat1,
  [aux_sym_execute_statement_arg_repeat1] = aux_sym_execute_statement_arg_repeat1,
  [aux_sym_select_list_repeat1] = aux_sym_select_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_go_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_func_proc_name_server_database_schema_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_statement_arg_named_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constant_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constant_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_specification_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_specification_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_elem_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_elem_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TODO] = {
    .visible = true,
    .named = true,
  },
  [sym_tsql_file] = {
    .visible = true,
    .named = true,
  },
  [sym_batch] = {
    .visible = true,
    .named = true,
  },
  [sym_go_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_body_batch] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_server_database_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_database_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_func_proc_name_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_statement_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_statement_arg_named] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_statement_arg_unnamed] = {
    .visible = true,
    .named = true,
  },
  [sym_execute_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_clauses] = {
    .visible = true,
    .named = true,
  },
  [sym_dml_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement_standalone] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_query_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_query_specification] = {
    .visible = true,
    .named = true,
  },
  [sym_select_list] = {
    .visible = true,
    .named = true,
  },
  [sym_select_list_elem] = {
    .visible = true,
    .named = true,
  },
  [sym_table_sources] = {
    .visible = true,
    .named = true,
  },
  [sym_table_source] = {
    .visible = true,
    .named = true,
  },
  [sym_table_source_item] = {
    .visible = true,
    .named = true,
  },
  [sym_full_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_id_] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tsql_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tsql_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_batch_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_body_batch_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_execute_statement_arg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_count = 1,
  field_database = 2,
  field_name = 3,
  field_procedure = 4,
  field_schema = 5,
  field_server = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_count] = "count",
  [field_database] = "database",
  [field_name] = "name",
  [field_procedure] = "procedure",
  [field_schema] = "schema",
  [field_server] = "server",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 2},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 3},
  [14] = {.index = 22, .length = 3},
  [15] = {.index = 25, .length = 3},
  [16] = {.index = 28, .length = 3},
  [17] = {.index = 31, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_procedure, 0},
  [1] =
    {field_count, 1},
  [2] =
    {field_value, 0},
  [3] =
    {field_procedure, 2},
  [4] =
    {field_procedure, 2},
    {field_schema, 0},
  [6] =
    {field_procedure, 3},
  [7] =
    {field_procedure, 3},
    {field_schema, 1},
  [9] =
    {field_name, 0},
    {field_value, 2},
  [11] =
    {field_database, 0},
    {field_procedure, 3},
  [13] =
    {field_procedure, 4},
    {field_schema, 2},
  [15] =
    {field_database, 1},
    {field_procedure, 4},
  [17] =
    {field_procedure, 4},
    {field_server, 0},
  [19] =
    {field_database, 0},
    {field_procedure, 4},
    {field_schema, 2},
  [22] =
    {field_database, 1},
    {field_procedure, 5},
    {field_schema, 3},
  [25] =
    {field_procedure, 5},
    {field_schema, 3},
    {field_server, 0},
  [28] =
    {field_database, 2},
    {field_procedure, 5},
    {field_server, 0},
  [31] =
    {field_database, 2},
    {field_procedure, 6},
    {field_schema, 4},
    {field_server, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 23,
  [52] = 52,
  [53] = 53,
  [54] = 22,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 32,
  [92] = 26,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 72,
  [99] = 65,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\'', 2,
        ',', 21,
        '-', 27,
        '.', 23,
        ';', 22,
        '=', 25,
        '@', 13,
        'N', 32,
        'T', 34,
        '[', 12,
        'F', 43,
        'f', 43,
        'G', 41,
        'g', 41,
        'S', 37,
        's', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '[') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 5:
      if (lookahead == ']') ADVANCE(46);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(29);
      END_STATE();
    case 12:
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 14:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\'', 2,
        ',', 21,
        '-', 27,
        '.', 23,
        ';', 22,
        '@', 13,
        'N', 1,
        'G', 10,
        'g', 10,
        'S', 7,
        's', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 15:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\'', 2,
        '-', 27,
        '.', 23,
        ';', 22,
        '@', 13,
        'N', 32,
        '[', 12,
        'G', 41,
        'g', 41,
        'S', 37,
        's', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 16:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        ',', 21,
        '.', 23,
        ';', 22,
        '[', 12,
        'F', 43,
        'f', 43,
        'G', 41,
        'g', 41,
        'S', 37,
        's', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(41);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_go_statement_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_go_statement_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_func_proc_name_server_database_schema_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_execute_statement_arg_named_token1);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_constant_token2);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_constant_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_query_specification_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_query_specification_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_query_specification_token2);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == '\'') ADVANCE(2);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'D') ADVANCE(35);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O') ADVANCE(33);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O') ADVANCE(47);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(44);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(38);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(31);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(20);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(40);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(42);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(30);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token1);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_select_list_elem_token2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_TODO);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 17},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 17},
  [29] = {.lex_state = 17},
  [30] = {.lex_state = 14},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 17},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 14},
  [39] = {.lex_state = 14},
  [40] = {.lex_state = 14},
  [41] = {.lex_state = 14},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 14},
  [44] = {.lex_state = 17},
  [45] = {.lex_state = 17},
  [46] = {.lex_state = 17},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 17},
  [55] = {.lex_state = 17},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 17},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 14},
  [62] = {.lex_state = 14},
  [63] = {.lex_state = 14},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 14},
  [72] = {.lex_state = 17},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 14},
  [76] = {.lex_state = 14},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 14},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 14},
  [81] = {.lex_state = 14},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 14},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 14},
  [92] = {.lex_state = 14},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 14},
  [95] = {.lex_state = 14},
  [96] = {.lex_state = 14},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 14},
  [99] = {.lex_state = 14},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_go_statement_token1] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym_func_proc_name_server_database_schema_token1] = ACTIONS(1),
    [aux_sym_execute_statement_arg_named_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_constant_token1] = ACTIONS(1),
    [aux_sym_constant_token2] = ACTIONS(1),
    [aux_sym_constant_token3] = ACTIONS(1),
    [aux_sym_query_specification_token1] = ACTIONS(1),
    [aux_sym_query_specification_token2] = ACTIONS(1),
    [aux_sym_select_list_elem_token1] = ACTIONS(1),
    [aux_sym_select_list_elem_token2] = ACTIONS(1),
    [anon_sym_TODO] = ACTIONS(1),
  },
  [1] = {
    [sym_tsql_file] = STATE(101),
    [sym_batch] = STATE(3),
    [sym_go_statement] = STATE(27),
    [sym_execute_body_batch] = STATE(9),
    [sym_func_proc_name_server_database_schema] = STATE(7),
    [sym_func_proc_name_database_schema] = STATE(42),
    [sym_func_proc_name_schema] = STATE(43),
    [sym_sql_clauses] = STATE(5),
    [sym_dml_clause] = STATE(49),
    [sym_select_statement_standalone] = STATE(55),
    [sym_select_statement] = STATE(53),
    [sym_query_expression] = STATE(52),
    [sym_query_specification] = STATE(50),
    [sym_id_] = STATE(19),
    [sym_keyword] = STATE(23),
    [aux_sym_tsql_file_repeat1] = STATE(3),
    [aux_sym_batch_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_go_statement_token1] = ACTIONS(5),
    [aux_sym_func_proc_name_server_database_schema_token1] = ACTIONS(7),
    [aux_sym_query_specification_token1] = ACTIONS(9),
    [aux_sym_select_list_elem_token1] = ACTIONS(11),
    [aux_sym_select_list_elem_token2] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      aux_sym_go_statement_token1,
    ACTIONS(20), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(23), 1,
      aux_sym_query_specification_token1,
    ACTIONS(26), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(29), 1,
      aux_sym_select_list_elem_token2,
    STATE(7), 1,
      sym_func_proc_name_server_database_schema,
    STATE(13), 1,
      sym_execute_body_batch,
    STATE(19), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
    STATE(27), 1,
      sym_go_statement,
    STATE(42), 1,
      sym_func_proc_name_database_schema,
    STATE(43), 1,
      sym_func_proc_name_schema,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(2), 2,
      sym_batch,
      aux_sym_tsql_file_repeat1,
    STATE(5), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [63] = 20,
    ACTIONS(5), 1,
      aux_sym_go_statement_token1,
    ACTIONS(7), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(9), 1,
      aux_sym_query_specification_token1,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_func_proc_name_server_database_schema,
    STATE(13), 1,
      sym_execute_body_batch,
    STATE(19), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
    STATE(27), 1,
      sym_go_statement,
    STATE(42), 1,
      sym_func_proc_name_database_schema,
    STATE(43), 1,
      sym_func_proc_name_schema,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(2), 2,
      sym_batch,
      aux_sym_tsql_file_repeat1,
    STATE(5), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [126] = 11,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(39), 1,
      aux_sym_query_specification_token1,
    ACTIONS(42), 1,
      aux_sym_select_list_elem_token1,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    STATE(28), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [164] = 11,
    ACTIONS(46), 1,
      aux_sym_go_statement_token1,
    ACTIONS(49), 1,
      aux_sym_query_specification_token1,
    ACTIONS(52), 1,
      aux_sym_select_list_elem_token1,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    STATE(33), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [202] = 9,
    ACTIONS(58), 1,
      aux_sym_query_specification_token1,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    ACTIONS(56), 2,
      aux_sym_go_statement_token1,
      aux_sym_select_list_elem_token1,
    STATE(6), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [234] = 10,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    ACTIONS(65), 1,
      aux_sym_execute_statement_arg_named_token1,
    ACTIONS(69), 1,
      aux_sym_constant_token2,
    STATE(59), 1,
      sym_execute_statement_arg,
    STATE(61), 1,
      sym_execute_statement_arg_named,
    STATE(71), 1,
      sym_execute_statement_arg_unnamed,
    STATE(75), 1,
      sym_constant,
    STATE(76), 1,
      sym_execute_parameter,
    ACTIONS(67), 2,
      aux_sym_constant_token1,
      aux_sym_constant_token3,
    ACTIONS(61), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [268] = 5,
    ACTIONS(77), 1,
      aux_sym_constant_token3,
    STATE(65), 1,
      sym_integer,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(73), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(75), 4,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
  [291] = 11,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      aux_sym_go_statement_token1,
    ACTIONS(81), 1,
      aux_sym_query_specification_token1,
    STATE(34), 1,
      sym_go_statement,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(90), 1,
      aux_sym_tsql_file_repeat2,
    STATE(4), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [326] = 4,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(83), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(85), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [345] = 4,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(90), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(92), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [364] = 4,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_select_list_repeat1,
    ACTIONS(96), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(98), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
  [383] = 9,
    ACTIONS(79), 1,
      aux_sym_go_statement_token1,
    ACTIONS(81), 1,
      aux_sym_query_specification_token1,
    STATE(29), 1,
      sym_go_statement,
    STATE(49), 1,
      sym_dml_clause,
    STATE(50), 1,
      sym_query_specification,
    STATE(52), 1,
      sym_query_expression,
    STATE(53), 1,
      sym_select_statement,
    STATE(55), 1,
      sym_select_statement_standalone,
    STATE(4), 2,
      sym_sql_clauses,
      aux_sym_batch_repeat1,
  [412] = 2,
    ACTIONS(102), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [426] = 2,
    ACTIONS(106), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [440] = 8,
    ACTIONS(65), 1,
      aux_sym_execute_statement_arg_named_token1,
    ACTIONS(69), 1,
      aux_sym_constant_token2,
    STATE(61), 1,
      sym_execute_statement_arg_named,
    STATE(71), 1,
      sym_execute_statement_arg_unnamed,
    STATE(75), 1,
      sym_constant,
    STATE(76), 1,
      sym_execute_parameter,
    STATE(78), 1,
      sym_execute_statement_arg,
    ACTIONS(67), 2,
      aux_sym_constant_token1,
      aux_sym_constant_token3,
  [466] = 9,
    ACTIONS(108), 1,
      aux_sym_go_statement_token1,
    ACTIONS(110), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(112), 1,
      aux_sym_select_list_elem_token2,
    STATE(44), 1,
      sym_full_table_name,
    STATE(45), 1,
      sym_table_source_item,
    STATE(46), 1,
      sym_table_source,
    STATE(47), 1,
      sym_table_sources,
    STATE(48), 1,
      sym_id_,
    STATE(51), 1,
      sym_keyword,
  [494] = 2,
    ACTIONS(116), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [508] = 2,
    ACTIONS(120), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(118), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [522] = 2,
    ACTIONS(124), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(122), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [536] = 2,
    ACTIONS(85), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
    ACTIONS(83), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [550] = 1,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [562] = 1,
    ACTIONS(126), 9,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [574] = 2,
    ACTIONS(130), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    ACTIONS(128), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [588] = 2,
    ACTIONS(134), 4,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_query_specification_token2,
      aux_sym_select_list_elem_token1,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [602] = 4,
    ACTIONS(138), 1,
      aux_sym_go_statement_token1,
    ACTIONS(141), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(26), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [619] = 3,
    STATE(33), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(52), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [634] = 4,
    ACTIONS(145), 1,
      aux_sym_go_statement_token1,
    ACTIONS(148), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(26), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [651] = 4,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(28), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [668] = 1,
    ACTIONS(150), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [679] = 3,
    ACTIONS(156), 1,
      aux_sym_query_specification_token2,
    ACTIONS(154), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [694] = 4,
    ACTIONS(77), 1,
      aux_sym_constant_token3,
    STATE(65), 1,
      sym_integer,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(73), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [711] = 4,
    ACTIONS(36), 1,
      aux_sym_go_statement_token1,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(26), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [728] = 5,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 1,
      aux_sym_go_statement_token1,
    ACTIONS(34), 2,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(42), 2,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    STATE(28), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [747] = 1,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [758] = 1,
    ACTIONS(167), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [769] = 1,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [780] = 1,
    ACTIONS(171), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [791] = 1,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [802] = 1,
    ACTIONS(175), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [813] = 1,
    ACTIONS(177), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [824] = 1,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [835] = 1,
    ACTIONS(181), 8,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_execute_statement_arg_named_token1,
      aux_sym_constant_token1,
      aux_sym_constant_token2,
      aux_sym_constant_token3,
      aux_sym_query_specification_token1,
  [846] = 2,
    ACTIONS(185), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [858] = 2,
    ACTIONS(189), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [870] = 2,
    ACTIONS(193), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [882] = 2,
    ACTIONS(197), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [894] = 2,
    ACTIONS(201), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [906] = 3,
    ACTIONS(207), 1,
      anon_sym_SEMI,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(205), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [920] = 2,
    ACTIONS(211), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [932] = 2,
    ACTIONS(213), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [944] = 2,
    ACTIONS(217), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [956] = 2,
    ACTIONS(221), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [968] = 2,
    ACTIONS(223), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [980] = 2,
    ACTIONS(227), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
    ACTIONS(225), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
  [992] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(231), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(15), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
  [1011] = 2,
    ACTIONS(233), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(235), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [1022] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(237), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(18), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
  [1041] = 4,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1056] = 4,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    STATE(68), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1071] = 2,
    STATE(62), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(249), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1082] = 2,
    STATE(67), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(251), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1093] = 2,
    STATE(68), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(251), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1104] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(253), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(24), 1,
      sym_id_,
  [1123] = 2,
    ACTIONS(255), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(257), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [1134] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(259), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(20), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
  [1153] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_execute_statement_arg_repeat1,
    ACTIONS(261), 4,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1166] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(266), 4,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1179] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(271), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(14), 1,
      sym_id_,
    STATE(23), 1,
      sym_keyword,
  [1198] = 6,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    ACTIONS(273), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(103), 1,
      sym_id_,
  [1217] = 2,
    STATE(63), 1,
      aux_sym_execute_body_batch_repeat1,
    ACTIONS(249), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1228] = 2,
    ACTIONS(275), 3,
      ts_builtin_sym_end,
      aux_sym_func_proc_name_server_database_schema_token1,
      aux_sym_select_list_elem_token2,
    ACTIONS(277), 3,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
      aux_sym_select_list_elem_token1,
  [1239] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(36), 1,
      sym_id_,
  [1255] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(37), 1,
      sym_id_,
  [1271] = 1,
    ACTIONS(279), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1279] = 1,
    ACTIONS(281), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1287] = 1,
    ACTIONS(283), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1295] = 1,
    ACTIONS(266), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1303] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(30), 1,
      sym_id_,
  [1319] = 1,
    ACTIONS(285), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1327] = 1,
    ACTIONS(261), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1335] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(39), 1,
      sym_id_,
  [1351] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(38), 1,
      sym_id_,
  [1367] = 1,
    ACTIONS(287), 5,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      anon_sym_COMMA,
      anon_sym_SEMI,
      aux_sym_query_specification_token1,
  [1375] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(40), 1,
      sym_id_,
  [1391] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(35), 1,
      sym_id_,
  [1407] = 4,
    ACTIONS(69), 1,
      aux_sym_constant_token2,
    STATE(75), 1,
      sym_constant,
    STATE(77), 1,
      sym_execute_parameter,
    ACTIONS(67), 2,
      aux_sym_constant_token1,
      aux_sym_constant_token3,
  [1421] = 5,
    ACTIONS(11), 1,
      aux_sym_select_list_elem_token1,
    ACTIONS(13), 1,
      aux_sym_select_list_elem_token2,
    ACTIONS(229), 1,
      aux_sym_go_statement_token1,
    STATE(23), 1,
      sym_keyword,
    STATE(41), 1,
      sym_id_,
  [1437] = 3,
    STATE(12), 1,
      sym_select_list_elem,
    STATE(31), 1,
      sym_select_list,
    ACTIONS(289), 2,
      aux_sym_select_list_elem_token1,
      aux_sym_select_list_elem_token2,
  [1448] = 3,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
    ACTIONS(293), 1,
      aux_sym_go_statement_token1,
    STATE(92), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [1459] = 3,
    ACTIONS(295), 1,
      aux_sym_constant_token3,
    STATE(99), 1,
      sym_integer,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
  [1470] = 3,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(297), 1,
      aux_sym_go_statement_token1,
    STATE(92), 2,
      sym_go_statement,
      aux_sym_tsql_file_repeat2,
  [1481] = 2,
    STATE(21), 1,
      sym_select_list_elem,
    ACTIONS(289), 2,
      aux_sym_select_list_elem_token1,
      aux_sym_select_list_elem_token2,
  [1489] = 1,
    ACTIONS(239), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1495] = 1,
    ACTIONS(300), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1501] = 1,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
      aux_sym_query_specification_token1,
  [1507] = 2,
    ACTIONS(65), 1,
      aux_sym_execute_statement_arg_named_token1,
    STATE(81), 1,
      sym_execute_statement_arg_named,
  [1514] = 1,
    ACTIONS(275), 2,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
  [1519] = 1,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      aux_sym_go_statement_token1,
  [1524] = 1,
    ACTIONS(302), 1,
      aux_sym_constant_token3,
  [1528] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
  [1532] = 1,
    ACTIONS(306), 1,
      anon_sym_EQ,
  [1536] = 1,
    ACTIONS(308), 1,
      aux_sym_func_proc_name_server_database_schema_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 164,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 234,
  [SMALL_STATE(8)] = 268,
  [SMALL_STATE(9)] = 291,
  [SMALL_STATE(10)] = 326,
  [SMALL_STATE(11)] = 345,
  [SMALL_STATE(12)] = 364,
  [SMALL_STATE(13)] = 383,
  [SMALL_STATE(14)] = 412,
  [SMALL_STATE(15)] = 426,
  [SMALL_STATE(16)] = 440,
  [SMALL_STATE(17)] = 466,
  [SMALL_STATE(18)] = 494,
  [SMALL_STATE(19)] = 508,
  [SMALL_STATE(20)] = 522,
  [SMALL_STATE(21)] = 536,
  [SMALL_STATE(22)] = 550,
  [SMALL_STATE(23)] = 562,
  [SMALL_STATE(24)] = 574,
  [SMALL_STATE(25)] = 588,
  [SMALL_STATE(26)] = 602,
  [SMALL_STATE(27)] = 619,
  [SMALL_STATE(28)] = 634,
  [SMALL_STATE(29)] = 651,
  [SMALL_STATE(30)] = 668,
  [SMALL_STATE(31)] = 679,
  [SMALL_STATE(32)] = 694,
  [SMALL_STATE(33)] = 711,
  [SMALL_STATE(34)] = 728,
  [SMALL_STATE(35)] = 747,
  [SMALL_STATE(36)] = 758,
  [SMALL_STATE(37)] = 769,
  [SMALL_STATE(38)] = 780,
  [SMALL_STATE(39)] = 791,
  [SMALL_STATE(40)] = 802,
  [SMALL_STATE(41)] = 813,
  [SMALL_STATE(42)] = 824,
  [SMALL_STATE(43)] = 835,
  [SMALL_STATE(44)] = 846,
  [SMALL_STATE(45)] = 858,
  [SMALL_STATE(46)] = 870,
  [SMALL_STATE(47)] = 882,
  [SMALL_STATE(48)] = 894,
  [SMALL_STATE(49)] = 906,
  [SMALL_STATE(50)] = 920,
  [SMALL_STATE(51)] = 932,
  [SMALL_STATE(52)] = 944,
  [SMALL_STATE(53)] = 956,
  [SMALL_STATE(54)] = 968,
  [SMALL_STATE(55)] = 980,
  [SMALL_STATE(56)] = 992,
  [SMALL_STATE(57)] = 1011,
  [SMALL_STATE(58)] = 1022,
  [SMALL_STATE(59)] = 1041,
  [SMALL_STATE(60)] = 1056,
  [SMALL_STATE(61)] = 1071,
  [SMALL_STATE(62)] = 1082,
  [SMALL_STATE(63)] = 1093,
  [SMALL_STATE(64)] = 1104,
  [SMALL_STATE(65)] = 1123,
  [SMALL_STATE(66)] = 1134,
  [SMALL_STATE(67)] = 1153,
  [SMALL_STATE(68)] = 1166,
  [SMALL_STATE(69)] = 1179,
  [SMALL_STATE(70)] = 1198,
  [SMALL_STATE(71)] = 1217,
  [SMALL_STATE(72)] = 1228,
  [SMALL_STATE(73)] = 1239,
  [SMALL_STATE(74)] = 1255,
  [SMALL_STATE(75)] = 1271,
  [SMALL_STATE(76)] = 1279,
  [SMALL_STATE(77)] = 1287,
  [SMALL_STATE(78)] = 1295,
  [SMALL_STATE(79)] = 1303,
  [SMALL_STATE(80)] = 1319,
  [SMALL_STATE(81)] = 1327,
  [SMALL_STATE(82)] = 1335,
  [SMALL_STATE(83)] = 1351,
  [SMALL_STATE(84)] = 1367,
  [SMALL_STATE(85)] = 1375,
  [SMALL_STATE(86)] = 1391,
  [SMALL_STATE(87)] = 1407,
  [SMALL_STATE(88)] = 1421,
  [SMALL_STATE(89)] = 1437,
  [SMALL_STATE(90)] = 1448,
  [SMALL_STATE(91)] = 1459,
  [SMALL_STATE(92)] = 1470,
  [SMALL_STATE(93)] = 1481,
  [SMALL_STATE(94)] = 1489,
  [SMALL_STATE(95)] = 1495,
  [SMALL_STATE(96)] = 1501,
  [SMALL_STATE(97)] = 1507,
  [SMALL_STATE(98)] = 1514,
  [SMALL_STATE(99)] = 1519,
  [SMALL_STATE(100)] = 1524,
  [SMALL_STATE(101)] = 1528,
  [SMALL_STATE(102)] = 1532,
  [SMALL_STATE(103)] = 1536,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0), SHIFT(32),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0), SHIFT(89),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 1, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0), SHIFT(32),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0), SHIFT(89),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_batch_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_statement, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_statement, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_select_list_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 4, 0, 7),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_schema, 3, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 3, 0, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_schema, 1, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 5, 0, 13),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 4, 0, 9),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_list_elem, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_list_elem, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_batch, 3, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_batch, 3, 0, 0), SHIFT(32),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_batch, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 7, 0, 17),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_specification, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_specification, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 1, 0, 0), REDUCE(sym_batch, 2, 0, 0),
  [161] = {.entry = {.count = 3, .reusable = false}}, REDUCE(aux_sym_tsql_file_repeat2, 1, 0, 0), REDUCE(sym_batch, 2, 0, 0), SHIFT(32),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 16),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 15),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 6, 0, 14),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 12),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 11),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 5, 0, 10),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 4, 0, 6),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_server_database_schema, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_proc_name_database_schema, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_source_item, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_source_item, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_source, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_source, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_sources, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table_sources, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_specification, 4, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_specification, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_table_name, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_table_name, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sql_clauses, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sql_clauses, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_expression, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query_expression, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_statement, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement_standalone, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_statement_standalone, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dml_clause, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dml_clause, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sql_clauses, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sql_clauses, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_statement, 2, 0, 2),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_statement, 2, 0, 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_execute_statement_arg_repeat1, 2, 0, 0),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_execute_statement_arg_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_execute_body_batch_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_execute_body_batch_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_parameter, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg_unnamed, 1, 0, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_statement_arg_named, 3, 0, 8),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tsql_file, 2, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tsql_file_repeat2, 2, 0, 0), SHIFT_REPEAT(91),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_execute_body_batch, 4, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [304] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_TSQL(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
